// Shared field and tool description strings used by both MCP server implementations.

export const D = {
  // IDs
  workspaceId: "Workspace ID (WKSP-xxxxxxxx) — use get_workspaces to find",
  projectId: "Project ID (PRJ-xxxxxxxx) — use get_projects to find",
  projectIdNarrow: "Narrow to a specific project (PRJ-xxxxxxxx); omit to search across all projects",
  taskId: "Ticket ID (e.g. EPIC-xxxxxxxx, US-xxxxxxxx, SPIKE-xxxxxxxx, BUG-xxxxxxxx)",
  sprintId: "Sprint ID (SPR-xxxxxxxx) to assign to a sprint, or null to place in the backlog",
  sprintIdFilter: "Filter by Sprint ID (SPR-xxxxxxxx), or null to get backlog items (no sprint assigned)",
  sprintIdMove: "Sprint ID (SPR-xxxxxxxx), or null to move to the backlog",
  sprintIdField: "Sprint ID (SPR-xxxxxxxx). Sprint IDs have prefix SPR-.",
  fixVersionId: "Release ID (RLS-xxxxxxxx) this is fixed in — 'version' and 'release' are the same concept in Flowboard",
  fixVersionIdFilter: "Filter by Release ID (RLS-xxxxxxxx)",
  fixVersionIdUpdate: "Release ID (RLS-xxxxxxxx)",
  epicId: "Parent Epic ID (EPIC-xxxxxxxx) — required for STORY and BUG issue types",
  epicIdFilter: "Filter by parent Epic ID (EPIC-xxxxxxxx) to get all stories/bugs under an epic",
  epicIdUpdate: "Parent Epic ID (EPIC-xxxxxxxx) — required for STORY and BUG",
  versionId: "Release ID (RLS-xxxxxxxx). Version IDs have prefix RLS-.",

  // Member fields
  assigneeId: "Firestore member document $id — use get_members to look up; differs from Firebase Auth userId",
  assigneeIdFilter: "Filter by member document $id (use get_members to find)",
  assigneeIdUpdate: "Member document $id — use get_members to look up",
  memberId: "Firestore member document $id (the $id field from get_members, not userId)",
  memberIdRemove: "Firestore member document $id to remove (the $id field from get_members, not userId)",
  userId: "The userId of the workspace member to add",

  // Ticket fields
  ticketName: "Title of the ticket",
  status: "Workflow status: BACKLOG, TODO, IN_PROGRESS, UNDER_REVIEW, or DONE",
  statusFilter: "Filter by workflow status",
  dueDate: "ISO date string (e.g. 2026-06-30)",
  issueType: "EPIC=large feature (EPIC-), STORY=user story (US-) needs epicId, SPIKE=investigation (SPIKE-), BUG=defect (BUG-) needs epicId+rca",
  issueTypeFilter: "Filter by issue type: EPIC, STORY, SPIKE, or BUG",
  issueTypeUpdate: "EPIC, STORY, SPIKE, or BUG",
  priority: "Priority: BLOCKER, HIGH, MEDIUM, LOW, or TRIVIAL",
  parentId: "Parent ticket ID for sub-tasks",
  storyPoints: "Story point estimate for effort sizing",
  storyPointsUpdate: "Story point estimate",
  originalEstimate: "Original time estimate in minutes (60 = 1 hour)",
  originalEstimateShort: "Original time estimate in minutes",
  remainingEstimate: "Remaining time estimate in minutes",
  labels: "Free-form label tags",
  acceptanceCriteria: "Acceptance Criteria — required for EPIC, STORY, and BUG issue types",
  acceptanceCriteriaUpdate: "Acceptance Criteria — required for EPIC, STORY, and BUG",
  rca: "Root Cause Analysis — required for BUG issue type",
  description: "Detailed description of the ticket",
  searchTicket: "Case-insensitive substring match on ticket name",

  // Worklog fields
  timeSpent: "Time spent in minutes",
  workDate: "ISO date string for when work was done",
  workDescription: "What was worked on",
  timeSpentUpdate: "Updated time spent in minutes",
  workDescriptionUpdate: "Updated description",

  // Link fields
  targetTaskId: "Target ticket ID to link to (e.g. EPIC-xxxxxxxx, BUG-xxxxxxxx)",
  linkType: "Relationship type — must be one of: BLOCKS, IS_BLOCKED_BY, RELATES_TO, DUPLICATES",

  // Tool-level descriptions
  createTicket: "Create a new Flowboard ticket. Issue types determine the ID prefix: EPIC (large feature, EPIC-xxxxxxxx), STORY (user story, US-xxxxxxxx, requires epicId), SPIKE (investigation/research, SPIKE-xxxxxxxx), BUG (defect, BUG-xxxxxxxx, requires epicId and rca). Use get_members to find the correct assigneeId.",
  getTickets: "Retrieve Flowboard tickets (Epics, Stories, Spikes, Bugs) with optional filtering. Returns up to 100 results sorted by creation date.",
  updateTicket: "Update fields on an existing Flowboard ticket (Epic, Story, Spike, or Bug). Only provided fields are updated.",
  deleteTicket: "Delete a ticket (task)",
  getWorkspaces: "List all Flowboard workspaces accessible to the authenticated user. The returned $id is the workspaceId (WKSP-xxxxxxxx) used in all other tools.",
  createWorkspace: "Create a new Flowboard workspace. Workspace IDs get prefix WKSP-. The creator is automatically added as a workspace ADMIN.",
  updateWorkspace: "Update an existing workspace",
  deleteWorkspace: "Delete a workspace",
  getProjects: "List projects within a workspace. Project IDs have prefix PRJ-. The returned $id is the projectId used in ticket and sprint tools.",
  createProject: "Create a new project within a workspace. Project IDs get prefix PRJ-.",
  updateProject: "Update an existing project",
  deleteProject: "Delete a project",
  getMembers: "List workspace members. The returned $id is the assigneeId to use when creating or filtering tickets. The userId field is the Firebase Auth uid (different from $id). Call this before create_ticket to find the correct assigneeId.",
  getProjectMembers: "List members of a specific project. Project members are a subset of workspace members and may have different roles.",
  updateMember: "Update a workspace member's role. Requires workspace ADMIN role. Note: memberId is the Firestore document $id from get_members, not the Firebase Auth userId.",
  removeMember: "Remove a member from a workspace. Admins can remove anyone; members can only remove themselves. Note: memberId is the Firestore document $id from get_members, not the Firebase Auth userId.",
  addProjectMember: "Add an existing workspace member to a specific project. The user must already be a member of the workspace (join via invite). Requires project admin or workspace admin role. Note: userId here is the Firebase Auth uid (the userId field from get_members, not the $id).",
  updateProjectMember: "Update a project member's role. Requires project admin or workspace admin role.",
  removeProjectMember: "Remove a member from a project. Workspace admins and project admins can remove anyone; members can remove themselves.",
  getSprints: "List sprints in a workspace. Sprint IDs have prefix SPR-. Each sprint follows a lifecycle: PLANNED → ACTIVE → COMPLETED.",
  createSprint: "Create a new sprint (SPR-xxxxxxxx) in a project. New sprints start in PLANNED status. Use start_sprint to activate.",
  updateSprint: "Update an existing sprint",
  startSprint: "Transition a PLANNED sprint to ACTIVE status. Only one sprint can be active per project at a time.",
  completeSprint: "Transition an ACTIVE sprint to COMPLETED status. Tickets that are not in DONE status are automatically moved to the backlog (sprintId set to null).",
  deleteSprint: "Delete a sprint. Only PLANNED sprints (not yet started) can be deleted. Any tickets assigned to the sprint are moved to the backlog.",
  getVersions: "List releases (versions) in a workspace. In Flowboard, 'version' and 'release' are the same concept — a versioned software release like v1.2.0. Release IDs have prefix RLS-. Lifecycle: UNRELEASED → RELEASED (or ARCHIVED).",
  createVersion: "Create a new release (version) in a project. Release IDs get prefix RLS-. New releases start in UNRELEASED status. Use fixVersionId on tickets to associate them with a release.",
  updateVersion: "Update name, description, or dates of a release (version). Version IDs have prefix RLS-.",
  releaseVersion: "Transition a release from UNRELEASED to RELEASED status.",
  archiveVersion: "Transition a release to ARCHIVED status.",
  deleteVersion: "Delete a release (version) and clear its fixVersionId from all associated tickets.",
  getWorklogs: "List time-tracking entries for a ticket. Entries are sorted newest-first.",
  logWork: "Log time worked on a ticket. Updates the ticket's timeSpent and remainingEstimate automatically.",
  updateWorklog: "Edit an existing work log entry (time spent or description). Adjusts the task's timeSpent accordingly.",
  deleteWorklog: "Delete a work log entry and reverse its time contribution from the task",
  getComments: "List comments on a task",
  addComment: "Add a comment to a task",
  updateComment: "Edit the content of an existing comment (only the comment author can edit)",
  deleteComment: "Delete a comment from a task (only the comment author can delete)",
  getTaskLinks: "List relationship links for a ticket. Each link has a type: BLOCKS, IS_BLOCKED_BY, RELATES_TO, or DUPLICATES.",
  addTaskLink: "Create a directional relationship between two Flowboard tickets.",
  deleteTaskLink: "Remove a link between tasks",
  getWorkspaceAnalytics: "Get ticket metrics for a workspace: total, assigned-to-me, incomplete, completed, and overdue counts. Each metric includes the current month value and the month-over-month difference.",
  getProjectAnalytics: "Get ticket metrics for a specific project: total, assigned-to-me, incomplete, completed, and overdue counts with month-over-month differences.",
} as const;
