// Generated by FlutterFire CLI. Run:
//   flutterfire configure --project=matrim-flowboard
//
// This file will be overwritten when you run flutterfire configure.
// Do NOT commit the real values — use CI environment variables for the
// google-services.json and regenerate this file in the CI setup script.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported by this app.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '${defaultTargetPlatform.name}. '
          'Run flutterfire configure to regenerate this file.',
        );
    }
  }

  // TODO: Run `flutterfire configure --project=matrim-flowboard` to populate
  // these values from your actual Firebase project.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'matrim-flowboard',
    storageBucket: 'matrim-flowboard.firebasestorage.app',
  );
}
